### ISSUE TITLE
Oprava úkolu

### ISSUE THREAD

**Issue by ifischerova** [MijaHinn/Zivotopis#1]
Ahoj Míšo, posílám zpětnou vazbu na první úkol. Dobrá práce, líbí se mi to  👍 :-) 
Na úpravu je tam jen pár drobností.

### index.html

**alt texty u fotografií/ikonek**
Alt text by měl co nejvíce vystihovat obsah/informaci obsažené ve fotce či ikonce. Pokud má obrázek spíš dekorativní formu, tak je alt text nadbytečný a nepřidává se. Alt text totiž není jen text, který se zobrazí při nenačtení obrázku/ikonky, ale zároveň ho čtou čtečky pro nevidomé uživatele webu.
Takže v tomto konkrétním případě by například u profilové fotografie mohlo být "profilová fotografie Michaely Hinnerové". 
 - [x] alt texty u fotografie
 
- [x] nechala bych VS Code ještě dokument zformátovat, hlavně kvůli správnému zanoření jednotlivých tagů.

Zajímavé je řešení nadpisů pracovních zkušeností pomocí tabulek => do budoucna je tohle ideální případ pro řešení přes flexbox ;-)
Dovednosti v html máš zalomené, ale v konečném CV jsou pak v jednom řádku, je to tak záměrně? :-) 

### style.css

**pseudotřídy**
- [x] pseudotřída :hover by měla být vždy dohromady s pseudotřídou :focus - díky ní se pak daný prvek chová vizuálně stejně jako při najetí myší i v případě, že se po stránce pohybuješ pomocí klávesnice.
- [x] nechala bych samostatně selektory ```menu a``` a ```kontakty a``` a do vícenásobného selektoru pseudotříd pak dala jen vlastnosti, kterými se od nich liší.

**Comment by MijaHinn** [comment]
Nahrála jsem opravenou verzi. Jinak ta sekce dovednosti - nejprve jsem dovednosti chtěla dát jednotlivě pod sebe, ale nakonec se to tam více hodilo za sebou. Tak jsem to dala do jednoho řádku a v html jsem to už pak zapomněla urpavit, tak proto to zůstalo pod sebou. :)

**Comment by ifischerova** [comment]
Ahoj Míšo, bezva práce 👍  
Jediná drobnost, u selektoru `menu a:hover` `menu a:focus` a `menu a:active` zůstala vlastnost `font-weight: bold;`, která je i u `menu a`, takže v těch pseudotřídách už to není třeba.
